version: 2.1

      
workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Run tests
          command: npm run tests
